// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEKL9CLj1QrI_AwD5Xa3QYakq18-8FhrI',
    appId: '1:375052010339:web:ffc05246aa901c0927c956',
    messagingSenderId: '375052010339',
    projectId: 'sokohub-7537b',
    authDomain: 'sokohub-7537b.firebaseapp.com',
    storageBucket: 'sokohub-7537b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbE6YpSHB0NN913XIikwaodWvLi6Fzco',
    appId: '1:375052010339:android:dc5cd41e160b074f27c956',
    messagingSenderId: '375052010339',
    projectId: 'sokohub-7537b',
    storageBucket: 'sokohub-7537b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbb0E5iZ-0Y3wJkk9fKl47cKnDeOszLc',
    appId: '1:375052010339:ios:ce28db99b039626027c956',
    messagingSenderId: '375052010339',
    projectId: 'sokohub-7537b',
    storageBucket: 'sokohub-7537b.firebasestorage.app',
    androidClientId: '375052010339-h2bll450l23s6shhtv1jc786n7h20ijd.apps.googleusercontent.com',
    iosClientId: '375052010339-44l4pt5dtvdhkgvpqkubn6tpatsktn6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokohubAdmin',
  );
}
